# Use the official Node.js 14 as a parent image
FROM ubuntu:22.04

# Set environment variables for version control and installation path (change the version as needed)
ENV TERRAFORM_VERSION=1.3.2
ENV TERRAFORM_DOWNLOAD_URL=https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
ENV TERRAFORM_DOWNLOAD_SHA256SUM=99fded2886ffaa5c8c9795b9656a6607ed5769d39539f4dabf7e7f0fc5e5e8e5

# Install required system packages
RUN apt-get update && \
    apt-get install -y curl unzip jq python3-pip && \
    curl -fsSL ${TERRAFORM_DOWNLOAD_URL} -o terraform.zip && \
    unzip terraform.zip -d /usr/local/bin && \
    rm terraform.zip

RUN pip3 install awscli awscli-local
    
RUN apt-get remove --purge -y unzip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN terraform version

COPY ./entry.sh /entry.sh
COPY ./provider.tf /provider.tf
RUN chmod +x /entry.sh

# Set the working directory in the container
WORKDIR /project

ENTRYPOINT [ "/entry.sh" ]